apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-time-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-time-app
  template:
    metadata:
      labels:
        app: sample-time-app
    spec:
      containers:
      - name: sample-time-app
        image: tw2883/sample-time-app:latest
        ports:
        - containerPort: 8080
